# Generated by Django 4.2.3 on 2023-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_url_pin_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="hashed_url",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
